---
- name: Deploy server
  hosts: web
  user: ubuntu
  sudo: yes
  vars:
    App_name: FlaskForm
    MySQL_root_pass: root
    ubuntu_required_packages:
      - libpq-dev
      - libmysqlclient-dev
      - libxml2-dev
      - libjpeg62
      - libjpeg62-dev
      - libfreetype6
      - libfreetype6-dev
      - zlib1g-dev
      - mysql-client
      - python-dev
      - python-setuptools
      - python-imaging
      - python-mysqldb
      - python-psycopg2
      - git-core
      - libapache2-mod-wsgi
      - php5
      - libapache2-mod-php5
      - php5-mcrypt
      - apache2
      - ufw
    pip_requerid_libraries:
      - virtualenv
      - flask
      - flask-mysql


  tasks:
    - include: install.yml
    - include: ufw.yml

    - name: Reboot server
      command: /sbin/reboot

    - name: Wait for the server to finish rebooting
      sudo: no
      local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300
